backend = "full"
color_space = "lch"
palette = "dark"

[templates]
hypr.template = 'hypr'
hypr.target = '~/.config/hypr/theme.conf'

waybar.template = 'waybar'
waybar.target = '~/.config/waybar/theme.css'

wofi.template = 'wofi'
wofi.target = '~/.config/wofi/theme.css'

swaync.template = 'swaync'
swaync.target = '~/.config/swaync/themes/wallust/colors-wallust.css'

