#!/bin/bash

backlight="intel_backlight"

base="/sys/class/backlight/${backlight}"
now="$(cat ${base}/brightness)"
max="$(cat ${base}/max_brightness)"

per=$(echo "scale=2;(${now}/${max})* 100" |bc| cut -d"." -f1)

echo "  ${per}%"
