#!/bin/sh

ai_provider="pollinations"

go() {
    name=go
    base=$HOME/repos/lab/go

    if command tmux has-session -t $name 2>/dev/null; then
        tmux a -t $name
        return
    fi

    tmux new -s $name -c $base \
        \; rename-window -t $name:0 vi \
        \; new-window -n run \
        \; new-window -n doc \
        \; new-window -n browser \
        \; next-window -t $name:0
}

main() {
    name="main"
    base=$HOME
    if command tmux has-session -t $name 2>/dev/null; then
        tmux a -t $name
    else
        tmux new -s $name -c $base \
            \; rename-window -t $name:0 vi \
            \; new-window -n man \
            \; new-window -n browser \
            \; new-window -n yt \
            \; next-window -t $name:0
    fi
}

cpp() {
    name="cpp"
    base=$HOME/repos/lab/cpp
    if command tmux has-session -t $name 2>/dev/null; then
        tmux a -t $name
    else
        tmux new -s $name -c $base \
            \; rename-window -t $name:0 vi \
            \; new-window -n run \
            \; new-window -n man \
            \; next-window -t $name:0
    fi
}

c() {
    name="c"
    base=$HOME/repos/lab/c
    if command tmux has-session -t $name 2>/dev/null; then
        tmux a -t $name
    else
        tmux new -s $name -c $base \
            \; rename-window -t $name:0 vi \
            \; new-window -n run \
            \; new-window -n man \
            \; next-window -t $name:0
    fi
}

web() {
    name="web"
    base=$HOME/repos/lab/web
    if command tmux has-session -t $name 2>/dev/null; then
        tmux a -t $name
    else
        tmux new -s $name -c $base \
            \; rename-window -t $name:0 vi-front \
            \; new-window -n vi-back \
            \; new-window -n man \
            \; new-window -n frontend \
            \; new-window -n backend \
            \; next-window -t $name:0
    fi
}

rust() {
    name="rust"
    base=$HOME/repos/lab/rust
    if command tmux has-session -t $name 2>/dev/null; then
        tmux a -t $name
    else
        tmux new -s $name -c $base \
            \; rename-window -t $name:0 vi \
            \; new-window -n run \
            \; new-window -n man \
            \; next-window -t $name:0
    fi
}
#if ! "$1" 2>/dev/null; then
#    echo "-_-" 1>&2
#fi

case "$1" in
go) go ;;
main) main ;;
cpp) cpp ;;
c) c ;;
web) web ;;
java) java ;;
rust) rust ;;
*) tmux a ;;
esac
