#!/bin/sh

go() {
    name=go
    base=$HOME/repos/lab/go
    if command tmux has-session -t $name 2>/dev/null; then
        tmux a -t $name
    else
        tmux new -s $name -c $base \
            \; rename-window -t $name:0 vi \
            \; new-window -n run \
            \; new-window -n $namedoc \
            \; new-window -n gpt "tgpt -i --provider duckduck$name" \
            \; new-window -n browser \
            \; next-window -t $name:0
    fi
}

main() {
    name="main"
    base=$HOME
    if command tmux has-session -t $name 2>/dev/null; then
        tmux a -t $name
    else
        tmux new -s $name -c $base \
            \; rename-window -t $name:0 vi \
            \; new-window -n man \
            \; new-window -n gpt "tgpt -i --provider duckduckgo" \
            \; new-window -n browser \
            \; new-window -n yt \
            \; next-window -t $name:0
    fi
}

cpp() {
    name="cpp"
    base=$HOME/repos/lab/cpp
    if command tmux has-session -t $name 2>/dev/null; then
        tmux a -t $name
    else
        tmux new -s $name -c $base \
            \; rename-window -t $name:0 vi \
            \; new-window -t run \
            \; new-window -t man \
            \; new-window -t gpt "tgpt -i --provider duckduckgo" \
            \; next-window -t $name:0
    fi
}
c() {
    name="c"
    base=$HOME/repos/lab/c
    if command tmux has-session -t $name 2>/dev/null; then
        tmux a -t $name
    else
        tmux new -s $name -c $base \
            \; rename-window -t $name:0 vi \
            \; new-window -n run \
            \; new-window -n man \
            \; new-window -n gpt "tgpt -i --provider duckduckgo" \
            \; next-window -t $name:0
    fi
}

case "$1" in
go) go ;;
main) main ;;
cpp) cpp ;;
c) c ;;
*) tmux a ;;
esac
