#!/bin/sh

empty() {
    test -z "$1" && return 1
}

get_ssid() {
    nmcli device wifi rescan
    ssid=$(nmcli -g ssid device wifi list | wofi --show dmenu)
}

connect() {
    nmcli device wifi connect "$1" 2>/dev/null
}

get_ssid
empty "$ssid" && exit
if connect "$ssid"; then
    notify-send Wifi "Connected to $ssid successfully"
fi
